name: Publish npm package & Create GitHub Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    
    # Only run when PR is merged, not when it's just closed without merging
    if: github.event.pull_request.merged == true
    
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - run: bun install

      # Build your package
      - run: bun run build
      
      # Extract version from package.json using Bun instead of Node
      - name: Get version from package.json
        id: package-version
        run: echo "VERSION=v$(bun -e "console.log(require('./package.json').version)")" >> $GITHUB_OUTPUT

      # Copy necessary files into dist
      - run: |
          cp package.json dist/
          cp README.md dist/
          [ -f LICENSE ] && cp LICENSE dist/ || true

      # Publish to npm from the build directory
      - name: Publish to npm
        working-directory: ./dist
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          bun publish --access public

      # Create a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ steps.package-version.outputs.VERSION }}
          name: Release ${{ steps.package-version.outputs.VERSION }}
          body: |
            Automated release for version ${{ steps.package-version.outputs.VERSION }}
            Merged PR: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
          draft: false
          prerelease: false