name: Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - run: bun install

      # Lint Check
      - name: Run Lint Check
        run: bun lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - run: bun install

      # run test
      - name: Run Tests
        run: bun test